---
deployment:
  tasks:
    - export DEPLOYPATH=/home/taptvyeo/public_html/
    - /bin/cp taptapdog.css $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp wu.html $DEPLOYPATH
    - /bin/cp wu_bart.html $DEPLOYPATH
    - /bin/cp wu_progress.html $DEPLOYPATH
    - /bin/cp wu_maps.html $DEPLOYPATH
    - /bin/cp ix_images/ix_taptapdog.png $DEPLOYPATH
    - /bin/cp ix_images/ix_me.png $DEPLOYPATH
    - /bin/cp ix_images/ix_wanders.png $DEPLOYPATH
    - /bin/cp ix_images/ix_tastynoms.png $DEPLOYPATH
    - /bin/cp wu_images/seal.jpg $DEPLOYPATH
    - /bin/cp wu_images/bart.png $DEPLOYPATH
    - /bin/cp wu_images/gandalf.png $DEPLOYPATH
    - /bin/cp wu_images/map.png $DEPLOYPATH
